use_frameworks!

platform :ios, '13.0'

target 'CustomPod_Example' do
  pod 'CustomPod', :git => 'https://github.com/edooktarifa/customPod'

  target 'CustomPod_Tests' do
    inherit! :search_paths

    
  end
end
